### ISSUE TITLE
nanquantile without modify reference

### ISSUE THREAD

**Issue by kongdd** [brenhinkeller/NaNStatistics.jl#16]
only nanquantile! is available in `NaNStatistics`. 
Is it possible to implement `nanquantile`?

**Comment by brenhinkeller** [comment]
Hmm, that would probably be easy enough

**Comment by brenhinkeller** [comment]
This should do it!

**Comment by brenhinkeller** [comment]
Note though that the in-place version will be substantially more efficient, so still try to use that when possible!

**Comment by kongdd** [comment]
Thanks for your quick action.

**Comment by kongdd** [comment]
It will be great if the new version is registered in Julia official mirror.

**Comment by kongdd** [comment]
Whether is it possible define q as a `Vector{Number}`? Otherwise, in that situation, `copyto!` and `sort` should be evaluated multiple times.
https://github.com/brenhinkeller/NaNStatistics.jl/blob/main/src/Sorting/nanpctile.jl#L92

**Comment by brenhinkeller** [comment]
All set on the version https://github.com/JuliaRegistries/General/pull/57785

Hmm, I think that gets trickier since we don't currently support vectors (or matrices or tensors) of percentiles in general, and dealing with all the possible multidimensional cases could get very complicated. If you need that, for now I'd probably suggest to make a single `copy` manually and then write a loop that uses the in-place `nanquantile!` on that

**Comment by kongdd** [comment]
Thanks for your suggestion. I will have a try.

**Comment by kongdd** [comment]
According to your suggestion, vector form `nanquantile` is: 
<https://github.com/jl-spatial/Ipaper.jl/blob/master/src/quantile.jl#L163>.
Further suggestion is welcome.

```julia
function nanquantile(A::AbstractArray{T,N}, probs::Vector{<:Real};
  dims::Integer=1, type=Float64) where {T,N}

  Aₜ = copyto!(Array{T,N}(undef, size(A)), A)

  Size = size(A) |> collect
  Size[dims] = length(probs)

  res = zeros(type, Size...)
  for k = 1:length(probs)
    q = probs[k]
    selectdim(res, dims, k) .= _nanquantile!(Aₜ, q, dims)
  end
  res
end
```
